spring:
  profiles: common

tencent:
  cloud:
    #腾讯云APPID
    appId: 1322602036
    #腾讯云SecretId
    secretId: AKIDeAjCZsVCcxKj4Ocow3HOSUYchlmkkswo
    #腾讯云SecretKey
    secretKey: ocM2d1GSUIwTvNo9MG7viQ1bHsS3hGwf
    region-public: ap-chengdu
    bucket-public: hxds-public-1322602036
    region-private: ap-chengdu
    bucket-private: hxds-private-1322602036

wx:
  app-id: wxc10cc5e635bc6da3
  app-secret: b93117013393b9416805da370ee7de0b
  mch-id: 123456
  key: 123456
  cert-path: E:/apiclient_cert.p12

minio:
  endpoint: http://localhost:9000
  access-key: root
  secret-key: abc123456

